spring:
  config:
    activate:
      on-profile: dev
    import: sm://

  cloud:
    gcp:
      secretmanager:
        enabled: true

  jpa:
    show-sql: false

  flyway:
    clean-disabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    com.bankflow: DEBUG
    org.flywaydb: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.cloud.gcp.secretmanager: DEBUG
