spring:
  config:
    activate:
      on-profile: dev

  cloud:
    gcp:
      secretmanager:
        enabled: true
        fail-fast: true

  jpa:
    show-sql: false

  flyway:
    clean-disabled: true

logging:
  level:
    com.bankflow: DEBUG
    org.flywaydb: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.jdbc.datasource: DEBUG
